name: Check links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude-path app
